travis:
  secure:
    BINSTAR_TOKEN: NCg3IZc21V6znppHcVNWXm2s3urWUwISPfyIqGyVUHbKQK8BV7teVUA7LnfvxeRnPzzD5oJhtiEwptikQTqXZBi77GWewpNNiuxjNjVDRohxjdGoCHYER8vNDT2JY6jzDPVbJAQbrNd2mBQDpeR9YsZJhkIp4uwWFCbtprXUXAcsJPAkljZFmE8E75aOGdXVaboNNNjd+Tquj6wlg5T6c4rm1riqajnCK5sYj6abXizC5R/HtjKxq+IFc+Jdk8URDrPTYshu9SAzQqgTH+uWcBEpYpHIgsBqz7H1KFXdnhYwyw4b92ki1qOwRW5O4B4sDX64my9rEqg5smvztPdVzOhFuKmhlJUCxbnKLM1H1nvR1ptzHQaUYZMaTKsknmKDb1qQxcYjKji/L/i3hzWf0p3v3LIy6uPd+zIE4X/Mkj81PO40GgvEOnyTDYH6y0lmx99pU73pz0qop9RD0NMOBeVIWwocnEVgzSy1P//eXsbwGEv6LuCK4VXKb9Qrn4eJbnsP67oghIrVBKKjmZjM0Tda0IrMCGk9V1aFPdwzTCTFj/K4WQ+XTAQvA0mdFtJdGmQTXeQDX2OaWKGNlgCkB6XApfEJqUGCxoYQDhr7ztyUtevoZ/YN2fP7QkHWRMW6LXoNs2TBYsJa75lOv9bqSanniwjzxHO4jij7xvklHTw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
