travis:
  secure:
    BINSTAR_TOKEN: CgmGsDBm3ss8Ua70Ny35sghCLAvtU9of2EkeUAJ7f3QUab5N/6vRI5zBWfyaICZyb1siwSpgT8zFQBejOQfph2Dvhw5CojgezNlvZrNhjxz3WYJ0waJfyrQAUeNWo8NHIrLM9HhHgdnCeLyFC36QcAr8vdU0Ttd7N5y8fTg2+LapAgQDD7Lgz9IHWKnmlZlPwNfiP7w6bS0aYiX6n5C+XcYewbeKcoWgu0DaDW1nmhWdycZa/BymNl82geeNaOwl9Q/EWv+lZ+NygwXY5xSjlhRAg/ModKwykord9XRvRf03ZxY5a/LwY0fZOEvHWNXfzdtPfNNd8+RyugxNu8ukeOnhl8fjrj0KN0q4OiPSErZIuTtokrF/hBbiPg95q7/Hv6hc3tpAHZVz7KQqhroAZiuCexnU1gB/kiNoLBlyScx8O/LLdxjK/xt7iCwHeWwgWviuDTSbhCQATPgmvEk6+AJ/D4XbfLlUs6TnMVDV3Y4F3wTEfn4mbSF4pnIY43roMgimflAgjxjvT3O5j98v/tZC/hxyN5eVvl132dNZwaS5QrrxfvFV2lHkI/ogmRK8Pom/FHX9dSSST0wWRYwhwa/Su67ZMnAFTp4F3BkZvzdvRNY2/9/o1ezzBu/8DMkS1vj392kam1XrAQSFNSeZ22Qks0Mx9z5kZL2J+NBsEJA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
